version: '3.7'

services:
  redis:
    image: redis/redis-stack
    container_name: my_redis
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
#      REDIS_PASSWORD: your_password_here
#      REDIS_CLUSTER_NODES: mymaster:mymaster_port,mynode1:mynode1_port,mynode2:mynode2_port
    volumes:
      - redis_data:/data

volumes:
  redis_data: